import * as theme from './theme';

export {
    theme,
}

export const FETCHING_MYPROFILE = 'FETCHING_MYPROFILE';
export const FETCH_MYPROFILE_SUCCESS = 'FETCH_MYPROFILE_SUCCESS';
export const FETCH_MYPROFILE_FAILURE = 'FETCH_MYPROFILE_FAILURE';

export const FETCHING_LOGTIME = 'FETCHING_LOGTIME';
export const FETCH_LOGTIME_SUCCESS = 'FETCH_LOGTIME_SUCCESS';
export const FETCH_LOGTIME_FAILURE = 'FETCH_LOGTIME_FAILURE';

export const FETCHING_LOCATION = 'FETCHING_LOCATION';
export const FETCH_LOCATION_z1_SUCCESS = 'FETCH_LOCATION_z1_SUCCESS';
export const FETCH_LOCATION_z2_SUCCESS = 'FETCH_LOCATION_z2_SUCCESS';
export const FETCH_LOCATION_z3_SUCCESS = 'FETCH_LOCATION_z3_SUCCESS';
export const FETCH_LOCATION_z4_SUCCESS = 'FETCH_LOCATION_z4_SUCCESS';
export const FETCH_LOCATION_FAILURE = 'FETCH_LOCATION_FAILURE';